
os: osx


before_install:
  - brew update

install:
  - brew install cppcheck qt@510
  # - brew install boost
  # - brew install llvm@3.7
  # - brew install netcdf
  # - 
script:
  - cd test/
  - qmake test.pro
  - make
