
os: osx
sudo: required


before_install:
  - brew update

install:
  - brew install cppcheck qt
  - brew link qt5 --force
  # - brew install boost
  # - brew install llvm@3.7
  # - brew install netcdf
  # - 
script:
  - cd test/
  - qmake test.pro
  - make
